title: Sport-Project
email: reigneps92@gmail.com
description: Worldwide Sport Site
baseurl: "/sport-project"
url: ""
twitter_username: yivanov
github_username: yivanov

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal